#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Organ.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Organ.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Organ.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Organ.clap"
exit 0
